apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: projet-eni
type: Opaque
data:
  # root password: rootpassword (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # database name: todolist (base64 encoded)
  mysql-database: dG9kb2xpc3Q=
  # mysql user: todouser (base64 encoded)
  mysql-user: dG9kb3VzZXI=
  # mysql password: todopass (base64 encoded)
  mysql-password: dG9kb3Bhc3M=
